### ISSUE TITLE
Issue while upgrading to MW_1.39 - deprecation

### ISSUE THREAD

**Issue by bertrandgorge** [Open-CSP/WikiSearch#40]
I all, I'm trying to upgrade our platform to MW1.39, and I have this issue with WikiSearch, that might probably be a compatibility issue between versions of ElasticSearch - PHP - SMW.... Any help would be very much appreciated!!!

php:8.2
elasticsearch:7.10.2
mediawiki/semantic-media-wiki:4.1.2
WikiSearch:master

```
[27-Nov-2023 09:03:27 UTC] PHP Deprecated:  Calling static trait method Elasticsearch\Namespaces\BooleanRequestWrapper::performRequest is deprecated, it should only be called on a class using the trait in /var/www/html/extensions/WikiSearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php on line 218
Elasticsearch\Common\Exceptions\BadRequest400Exception from line 657 of /var/www/html/extensions/WikiSearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php: null
#0 /var/www/html/extensions/WikiSearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(312): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array)
#1 /var/www/html/extensions/WikiSearch/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#2 /var/www/html/extensions/WikiSearch/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php(65): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#3 /var/www/html/extensions/WikiSearch/vendor/ezimuel/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#4 /var/www/html/extensions/WikiSearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(235): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#5 /var/www/html/extensions/WikiSearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(204): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#6 /var/www/html/extensions/WikiSearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(115): Elasticsearch\Connections\Connection->performRequest('HEAD', '/smw-data-wiki', Array, NULL, Array, Object(Elasticsearch\Transport))
#7 /var/www/html/extensions/WikiSearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/BooleanRequestWrapper.php(44): Elasticsearch\Transport->performRequest('HEAD', '/smw-data-wiki', Array, NULL, Array)
#8 /var/www/html/extensions/WikiSearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(218): Elasticsearch\Namespaces\BooleanRequestWrapper::performRequest(Object(Elasticsearch\Endpoints\Indices\Exists), Object(Elasticsearch\Transport))
#9 /var/www/html/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rebuilder/Rollover.php(107): Elasticsearch\Namespaces\IndicesNamespace->exists(Array)
#10 /var/www/html/extensions/SemanticMediaWiki/src/Elastic/Installer.php(54): SMW\Elastic\Indexer\Rebuilder\Rollover->update('data')
#11 /var/www/html/extensions/SemanticMediaWiki/src/Elastic/ElasticStore.php(328): SMW\Elastic\Installer->setup()
#12 /var/www/html/extensions/SemanticMediaWiki/src/Store.php(490): SMW\Elastic\ElasticStore->setup(Object(SMW\Options))
#13 /var/www/html/includes/installer/DatabaseUpdater.php(547): SMW\Store::setupStore(true, Object(SMW\Options))
#14 /var/www/html/includes/installer/DatabaseUpdater.php(515): DatabaseUpdater->runUpdates(Array, true)
#15 /var/www/html/maintenance/update.php(209): DatabaseUpdater->doUpdates(Array)
#16 /var/www/html/maintenance/includes/MaintenanceRunner.php(309): UpdateMediaWiki->execute()
#17 /var/www/html/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#18 /var/www/html/maintenance/update.php(319): require_once('/var/www/html/m...')
#19 {main}
```

**Comment by bertrandgorge** [comment]
Fixed by using ES6.8...
